### ISSUE TITLE
Convert the main screen into a proper class that extends `Screen`

### ISSUE THREAD

**Issue by l2lam** [l2lam/Word-guessing-game-demo#28]
Currently the main/start screen is just hacked together in `main.js`.  But we now have a `Screen` class that is the basis for screens in our program.

**Comment by rrohith-git** [comment]
Hi, I would like to take up this issue. Can you elaborate bit more on to this issue

**Comment by l2lam** [comment]
All screens should extend the `Screen` class, similar to `Game`, `ConfigurationScreen`.  Consider using the new `PaintedButton` on the main screen rather than the current HTML buttons to make the UI look more uniform.
